"""add persona

Revision ID: a5640771b3d2
Revises: 
Create Date: 2025-10-22 00:54:32.622560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5640771b3d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('public_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('profile_image_url', sa.String(length=512), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_is_active'), 'personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_personas_username'), 'personas', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_username'), table_name='personas')
    op.drop_index(op.f('ix_personas_is_active'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
